export const Constants = {
    SET_HOTEL_ID: 'SET_HOTEL_ID',
    SET_SEARCH_FORM: 'SET_SEARCH_FORM',
    SET_USER_ID: 'SET_USER_ID',
    SET_BOOKING_HISTORIES: 'SET_BOOKING_HISTORIES',
    SET_NAME_USER: 'SET_NAME_USER'  
};